import { Board } from '../types.ts'

const startingBoard: Board = [
  [
    { square: 'a8', type: 'r', color: 'b' },
    { square: 'b8', type: 'n', color: 'b' },
    { square: 'c8', type: 'b', color: 'b' },
    { square: 'd8', type: 'q', color: 'b' },
    { square: 'e8', type: 'k', color: 'b' },
    { square: 'f8', type: 'b', color: 'b' },
    { square: 'g8', type: 'n', color: 'b' },
    { square: 'h8', type: 'r', color: 'b' },
  ],
  [
    { square: 'a7', type: 'p', color: 'b' },
    { square: 'b7', type: 'p', color: 'b' },
    { square: 'c7', type: 'p', color: 'b' },
    { square: 'd7', type: 'p', color: 'b' },
    { square: 'e7', type: 'p', color: 'b' },
    { square: 'f7', type: 'p', color: 'b' },
    { square: 'g7', type: 'p', color: 'b' },
    { square: 'h7', type: 'p', color: 'b' },
  ],
  [
    { square: 'a6' },
    { square: 'b6' },
    { square: 'c6' },
    { square: 'd6' },
    { square: 'e6' },
    { square: 'f6' },
    { square: 'g6' },
    { square: 'h6' },
  ],
  [
    { square: 'a5' },
    { square: 'b5' },
    { square: 'c5' },
    { square: 'd5' },
    { square: 'e5' },
    { square: 'f5' },
    { square: 'g5' },
    { square: 'h5' },
  ],
  [
    { square: 'a4' },
    { square: 'b4' },
    { square: 'c4' },
    { square: 'd4' },
    { square: 'e4' },
    { square: 'f4' },
    { square: 'g4' },
    { square: 'h4' },
  ],
  [
    { square: 'a3' },
    { square: 'b3' },
    { square: 'c3' },
    { square: 'd3' },
    { square: 'e3' },
    { square: 'f3' },
    { square: 'g3' },
    { square: 'h3' },
  ],
  [
    { square: 'a2', type: 'p', color: 'w' },
    { square: 'b2', type: 'p', color: 'w' },
    { square: 'c2', type: 'p', color: 'w' },
    { square: 'd2', type: 'p', color: 'w' },
    { square: 'e2', type: 'p', color: 'w' },
    { square: 'f2', type: 'p', color: 'w' },
    { square: 'g2', type: 'p', color: 'w' },
    { square: 'h2', type: 'p', color: 'w' },
  ],
  [
    { square: 'a1', type: 'r', color: 'w' },
    { square: 'b1', type: 'n', color: 'w' },
    { square: 'c1', type: 'b', color: 'w' },
    { square: 'd1', type: 'q', color: 'w' },
    { square: 'e1', type: 'k', color: 'w' },
    { square: 'f1', type: 'b', color: 'w' },
    { square: 'g1', type: 'n', color: 'w' },
    { square: 'h1', type: 'r', color: 'w' },
  ],
]

startingBoard.reverse()

export default startingBoard
