name: Test

on: push

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: v1.x
      - run: deno fmt --check
      - run: deno lint

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: v1.x
      - run: deno test

  coverage:
    runs-on: ubuntu-22.04
    steps:
      - uses: codecov/codecov-action@v3
